TurtleProgram
int TurtleProgram::size
Referenced by getLength, makeString, operator*=, operator+=, operator=, operator==, TurtleProgram.
std::string* TurtleProgram::dirLenArr
Referenced by getIndex, makeString, operator*=, operator+=, operator=, operator==, setIndex, TurtleProgram, ~TurtleProgram.
TurtleProgram::TurtleProgram()
TurtleProgram::TurtleProgram(const TurtleProgram &tp)
References dirLenArr, size.
TurtleProgram::TurtleProgram(const std::string &dir, const std::string &len)
TurtleProgram::~TurtleProgram()
References dirLenArr.
std::string TurtleProgram::makeString() const
References dirLenArr, size.
Referenced by operator<<.
bool TurtleProgram::operator==(const TurtleProgram &rhs)
References dirLenArr, size.
bool TurtleProgram::operator!=(const TurtleProgram &rhs)
TurtleProgram & TurtleProgram::operator=(const TurtleProgram &rhs)
References dirLenArr, size.
TurtleProgram & TurtleProgram::operator=(const TurtleProgram *const rhs)
References dirLenArr, size.
const TurtleProgram TurtleProgram::operator+(const TurtleProgram &rhs) const
const TurtleProgram TurtleProgram::operator+(const TurtleProgram *const rhs) const
TurtleProgram & TurtleProgram::operator+=(const TurtleProgram &rhs)
References dirLenArr, size.
TurtleProgram & TurtleProgram::operator+=(const TurtleProgram *const rhs)
const TurtleProgram TurtleProgram::operator*(const int &rhs) const
const TurtleProgram TurtleProgram::operator*(const int *const rhs) const
TurtleProgram & TurtleProgram::operator*=(const int &rhs)
References dirLenArr, size.
TurtleProgram & TurtleProgram::operator*=(const int *const rhs)
const int TurtleProgram::getLength() const
References size.
Referenced by getIndex, setIndex.
std::string & TurtleProgram::getIndex(const int &pos) const
References dirLenArr, getLength.
Referenced by getIndex, main.
std::string & TurtleProgram::getIndex(const int *const pos) const
References getIndex.
bool TurtleProgram::setIndex(const int &pos, const std::string &val)
References dirLenArr, getLength.
Referenced by setIndex.
bool TurtleProgram::setIndex(const int &pos, std::string *const val)
References setIndex.
std::ostream& operator<<(std::ostream &os, const TurtleProgram &tp)
std::ostream& operator<<(std::ostream &os, const TurtleProgram *const tp)